clean:
  image: registry.papierpain.fr/docker/alpine:latest
  script:
    - ./main.sh ${TOKEN_ASPIRATEUR}

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
