clean:
  pre_script:
    - apk update
    - apk add jq
    - chmod +x main.sh
    - chmod +x functions/*.sh
  script:
    - ./main.sh ${TOKEN_ASPIRATEUR}
  only:
    - master

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
