clean:
  before_script:
    - apk update
    - apk add jq bash curl
  script:
    - ./main.sh ${TOKEN_ASPIRATEUR}
  only:
    - master

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
