stages:
  - clean

clean:
  stage: clean
  tags:
    - shell
  script:
    - ./main.sh ${TOKEN_ASPIRATEUR}
  only:
    - master

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
